name: 'Build and deploy to S3'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [ opened, synchronize ]
#oidc encima de oauth 2.0
permissions:
  id-token: write
  contents: read

jobs:
  avoid_reduncy:
    runs-on: ubuntu-22.04
    steps:
      - name: Cancel Previous builds
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  #  lint:
  #    runs-on: ubuntu-22.04
  #    steps:
  #      - uses: actions/checkout@v3
  #        with:
  #          fetch-depth: 0
  #
  #      - uses: actions/setup-node@v3
  #        with:
  #          node-version: 14
  #          cache: 'npm'
  #
  #      - name: install
  #        run: npm ci --no-audit --no-fund
  #
  #      - name: Lint
  #        run: npm run eslint

  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'npm'

      - name: install
        run: npm ci --no-audit --no-fund

      - name: compile dist
        run: npm run build

      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist

  deploy:
    runs-on: ubuntu-22.04

    steps:
      - needs: [ build ]
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist

      - name: Configure AWS Credentials
        if: ${{ github.event_name == 'push' }}
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.S3_BUCKET_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT }}:role/track3-front-s3-role
          role-session-name: GithubSession # OIDC

      - name: Check login
        if: ${{ github.event_name == 'push' }}
        run: aws sts get-caller-identity

      - name: Upload to S3
        if: ${{ github.event_name == 'push' }}
        run: aws s3 sync ./dist s3://${{ secrets.S3_BUCKET }} --delete